### ISSUE TITLE
Identify necessary config for heroku

### ISSUE THREAD

**Issue by Woodentyler** [Woodentyler/HelpOut#6]

**Comment by anastassia-b** [comment]
Please set up your heroku domain and complete the first push. Leave the link as a comment and I will close this issue.

**Comment by anastassia-b** [comment]
Thanks. Switch to a custom domain name or more descriptive heroku domain when you can!

**Comment by Woodentyler** [comment]
Initial heroku deployment complete. Thanks!

**Comment by Woodentyler** [comment]
https://help-out-full-stack-project.herokuapp.com/

Updated heroku link!
